REGEX_EXPRESSIONS_TO_MASK:dict = {
    'password':[
        r"password[:=]\s{0,2}[^\s]+",
        r"pass[:=]\s{0,2}[^\s]+",
        r"passwd[:=]\s{0,2}[^\s]+",
        r"pwd[:=]\s{0,2}[^\s]+",
    ],
    'token':[
        r"token[:=]\s{0,2}[^\s]+",
        r"bearer[:=]\s{0,2}[^\s]+",
        r"x-vault-token[:=]\s{0,2}[^\s]+",
        r"x-token[:=]\s{0,2}[^\s]+",
    ],
    'api_key':[
        r"api_key[:=]\s{0,2}[^\s]+",
        r"x-api-key[:=]\s{0,2}[^\s]+",
        r"x-aws-api-key[:=]\s{0,2}[^\s]+",
    ],
    'credentials':[
        r"AWS_SECRET_ACCESS_KEY[:=]\s{0,2}[^\s]+",
        r"AWS_ACCESS_KEY_ID[:=]\s{0,2}[^\s]+",
        r"AWS_SESSION_TOKEN[:=]\s{0,2}[^\s]+",
        r"credentials[:=]\s{0,2}[^\s]+",
        r"creds[:=]\s{0,2}[^\s]+",
    ],
    'iam_role':[
        r"role[:=]\s{0,2}[^\s]+",
        r"iam role[:=]\s{0,2}[^\s]+",
    ],
    'secret':[
        r"secret[:=]\s{0,2}[^\s]+",
        r"secrets[:=]\s{0,2}[^\s]+",
    ],
    'secret_key':[
        r"secret_key[:=]\s{0,2}[^\s]+",
    ],
    'authorization':[
        r"authorization[:=]\s{0,2}basic\s{0,2}[^\s]+",
        r"authorization[:=]\s{0,2}bearer\s{0,2}[^\s]+",
        r"authorization[:=]\s{0,2}[^\s]+",
    ],
    'oauth_artifacts':[
        r"oauth_token[:=]\s{0,2}[^\s]+",
        r"oauth_nonce[:=]\s{0,2}[^\s]+",
        r"oauth_signature[:=]\s{0,2}[^\s]+",
        r"oauth_consumer_key[:=]\s{0,2}[^\s]+",
        r"jwt[:=]\s{0,2}[^\s]+",
    ],
}